### ISSUE TITLE
[1.19.2] Only Single Block Mining in all Modes

### ISSUE THREAD

**Issue by kaffeekirsche** [DAQEM/JobsPlus-Archive#51]
Is it necessary to recraft tools since the latest update? My hammer and shovel only work in single block mode and no longer in 3x3 and 3x3x3 mode

**Comment by DAQEM** [comment]
Nope, this must be a bug, let me check.

**Comment by kaffeekirsche** [comment]
Okay, the Axe works normal and the Pickaxe Ore Vain Mining works normal. Only the 3x3, 3x3x3 and 5x5 Mode not working. Highter Tiers i have not checked

**Comment by DAQEM** [comment]
Yeah I've tested with Emerald tools. They don't work. I'm going to upload a fix asap.

**Comment by DAQEM** [comment]
What version of the game are you playing? 1.19.2 or 1.18.2?

**Comment by kaffeekirsche** [comment]
Oh Sorry im on 1.19.2, have forgotten paste it in the title

**Comment by DAQEM** [comment]
When you mine a block, does it say this?
![](https://i.imgur.com/EtsNrtD.png)

**Comment by kaffeekirsche** [comment]
Still a small error, no idea whether it is related to the other one. if you have Ore Vain Mining active, not only the ore but also the area is removed from the mode, i.e. 3x3 ...

**Comment by kaffeekirsche** [comment]
> When you mine a block, does it say this? ![](https://camo.githubusercontent.com/8bb68d989e64ceae71960b734938509bab35b42d91ecbc88328359531ce934c4/68747470733a2f2f692e696d6775722e636f6d2f4574734e7274442e706e67)

I have no feedback in chat. it only not working without an error/message

**Comment by DAQEM** [comment]
I think I found the cause. The mod doesn't disable veinminer anymore. So it thinks you're veinmining all the time. If you restart your world and don't press the veinminer button and try to use the 3x3 it should work just fine. Can you test this for me so I know for sure you are experiencing the same problem?

**Comment by kaffeekirsche** [comment]
u mean, disable vein mining in job menu, restart world and test with disabled vein mining?

**Comment by DAQEM** [comment]
Correct.

**Comment by kaffeekirsche** [comment]
https://vimeo.com/771202266

1. Disabele Vein Mining
2. Restart Server
3. 3x3 3x3x3 ... Modes working
4. Activate Vein Mining not working

**Comment by DAQEM** [comment]
Fixed it. I'll upload it to CurseForge asap.

**Comment by pandory-network** [comment]
Hello, sorry but unfortunately the bug is still present in the new update.
